/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/login/": {
    /** Login */
    post: operations["login_login__post"];
  };
  "/gened/": {
    /** Getgenedcredit */
    get: operations["getGenEdCredit_gened__get"];
  };
  "/gened/subjectlist": {
    /** Subjectlist */
    get: operations["subjectlist_gened_subjectlist_get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** GenEdResponseDto */
    GenEdResponseDto: {
      /** Wellness */
      Wellness: number;
      /** Entrepreneurship */
      Entrepreneurship: number;
      /** Thai Citizen And Global Citizen */
      Thai_Citizen_and_Global_Citizen: number;
      /** Language And Communication */
      Language_and_Communication: number;
      /** Aesthetics */
      Aesthetics: number;
      /** Others */
      Others: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** LoginBodyDto */
    LoginBodyDto: {
      /** Username */
      username: string;
      /** Password */
      password: string;
    };
    /** SubjectDto */
    SubjectDto: {
      /** Subject Code */
      subject_code: string;
      /** Subject Name En */
      subject_name_en: string;
      /** Subject Name Th */
      subject_name_th: string;
      /** Credits */
      credits: number;
    };
    /** SubjectListResponseDto */
    SubjectListResponseDto: {
      /** Wellness */
      Wellness: components["schemas"]["SubjectDto"][];
      /** Entrepreneurship */
      Entrepreneurship: components["schemas"]["SubjectDto"][];
      /** Thai Citizen And Global Citizen */
      Thai_Citizen_and_Global_Citizen: components["schemas"]["SubjectDto"][];
      /** Language And Communication */
      Language_and_Communication: components["schemas"]["SubjectDto"][];
      /** Aesthetics */
      Aesthetics: components["schemas"]["SubjectDto"][];
      /** Others */
      Others: components["schemas"]["SubjectDto"][];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Login */
  login_login__post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginBodyDto"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Getgenedcredit */
  getGenEdCredit_gened__get: {
    parameters: {
      query: {
        stdid: string;
      };
      header?: {
        "x-access-token"?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["GenEdResponseDto"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Subjectlist */
  subjectlist_gened_subjectlist_get: {
    parameters: {
      query: {
        stdid: string;
      };
      header?: {
        "x-access-token"?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SubjectListResponseDto"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
